package com.examen.agenda.corpotativa.utils;

public class JsonTestResponse {
	
	public static final String JSON_BUSQUEDA_INDIVIDUAL = "{"
			+ "  \"mensaje\": \"Operación Exitosa\","
			+ "  \"folio\": \"xFqqcxnjdRpBRlwIEtJe*29-08-2022 10:53:50\","
			+ "  \"resultado\": {"
			+ "    \"idTipoDispositivo\": 1,"
			+ "    \"descripcionDispositivo\": \"MULTIFUNCIONAL\","
			+ "    \"idDispositivo\": \"WS_KIOSK01\","
			+ "    \"numeroEmpleadoDispositivo\": \"999980\","
			+ "    \"solicitudes\": ["
			+ "      {"
			+ "        \"idTipoSolicitud\": 1,"
			+ "        \"descripcionSolicitud\": \"Billetes\","
			+ "        \"idTipoOperacion\": 1,"
			+ "        \"descripcionTipoOperacion\": \"DOTACION\","
			+ "        \"numeroSolicitud\": 1,"
			+ "        \"idDivisa\": 1,"
			+ "        \"descripcionDivisa\": \"MXN\","
			+ "        \"idEstatus\": 2,"
			+ "        \"descripcionEstatus\": \"AUTORIZADA\","
			+ "        \"saldoSolicitado\": 50000,"
			+ "        \"fechaSolicitud\": \"2022-12-10 13:30:50\","
			+ "        \"fechaAutorizada\": \"2022-12-10 13:31:00\","
			+ "        \"numeroEmpleadoAutorizante\": \"1002544\","
			+ "        \"numeroEmpleado\": \"59905\","
			+ "        \"idOperacionOrigen\": 1,"
			+ "        \"descripcionOrigen\": \"ADN\","
			+ "        \"DetalleSolicitud\": ["
			+ "          {"
			+ "            \"idTipoContenedor\": 1,"
			+ "            \"denominaciones\": ["
			+ "              {"
			+ "                \"id\": 1000,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 20"
			+ "              },"
			+ "              {"
			+ "                \"id\": 500,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 5"
			+ "              }"
			+ "            ]"
			+ "          },"
			+ "          {"
			+ "            \"idTipoContenedor\": 2,"
			+ "            \"denominaciones\": ["
			+ "              {"
			+ "                \"id\": 1000,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 20"
			+ "              },"
			+ "              {"
			+ "                \"id\": 500,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 5"
			+ "              }"
			+ "            ]"
			+ "          }"
			+ "        ]"
			+ "      }"
			+ "    ]"
			+ "  }"
			+ "}";
	
	public static final String JSON_BUSQUEDA_UNIVERSO ="{"
			+ "  \"mensaje\": \"Operación Exitosa\","
			+ "  \"folio\": \"xFqqcxnjdRpBRlwIEtJe*29-08-2022 10:53:50\","
			+ "  \"resultado\": {"
			+ "    \"idTipoDispositivo\": 1,"
			+ "    \"descripcionDispositivo\": \"MULTIFUNCIONAL\","
			+ "    \"idDispositivo\": \"WS_KIOSK01\","
			+ "    \"numeroEmpleadoDispositivo\": \"999980\","
			+ "    \"solicitudes\": ["
			+ "      {"
			+ "        \"idTipoOperacion\": 1,"
			+ "        \"descripcionTipoOperacion\": \"DOTACION\","
			+ "        \"numeroSolicitud\": 1,"
			+ "        \"idDivisa\": 1,"
			+ "        \"descripcionDivisa\": \"MXN\","
			+ "        \"idEstatus\": 2,"
			+ "        \"descripcionEstatus\": \"AUTORIZADA\","
			+ "        \"saldoSolicitado\": 50000,"
			+ "        \"fechaSolicitud\": \"2022-12-10 13:30:50\","
			+ "        \"fechaAutorizada\": \"2022-12-10 13:31:00\","
			+ "        \"numeroEmpleadoAutorizante\": \"1002544\","
			+ "        \"numeroEmpleado\": \"59905\","
			+ "        \"idOperacionOrigen\": 1,"
			+ "        \"descripcionOrigen\": \"ADN\","
			+ "        \"DetalleSolicitud\": ["
			+ "          {"
			+ "            \"idTipoContenedor\": 1,"
			+ "            \"denominaciones\": ["
			+ "              {"
			+ "                \"id\": 1000,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 20"
			+ "              },"
			+ "              {"
			+ "                \"id\": 500,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 5"
			+ "              }"
			+ "            ]"
			+ "          },"
			+ "          {"
			+ "            \"idTipoContenedor\": 2,"
			+ "            \"denominaciones\": ["
			+ "              {"
			+ "                \"id\": 1000,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 20"
			+ "              },"
			+ "              {"
			+ "                \"id\": 500,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 5"
			+ "              }"
			+ "            ]"
			+ "          }"
			+ "        ]"
			+ "      },"
			+ "      {"
			+ "        \"idTipoOperacion\": 2,"
			+ "        \"descripcionTipoOperacion\": \"CONCENTRACION\","
			+ "        \"numeroSolicitud\": 2,"
			+ "        \"idDivisa\": 1,"
			+ "        \"descripcionDivisa\": \"MXN\","
			+ "        \"idEstatus\": 2,"
			+ "        \"descripcionEstatus\": \"AUTORIZADA\","
			+ "        \"saldoSolicitado\": 50000,"
			+ "        \"saldoConfrimado\": 49000,"
			+ "        \"fechaSolicitud\": \"2022-12-10 13:30:50\","
			+ "        \"fechaAutorizada\": \"2022-12-10 13:31:00\","
			+ "        \"numeroEmpleadoAutorizante\": \"1002544\","
			+ "        \"numeroEmpleado\": \"59905\","
			+ "        \"idOperacionOrigen\": 1,"
			+ "        \"descripcionOrigen\": \"ADN\","
			+ "        \"DetalleSolicitud\": ["
			+ "          {"
			+ "            \"idTipoContenedor\": 1,"
			+ "            \"denominaciones\": ["
			+ "              {"
			+ "                \"id\": 1000,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 20"
			+ "              },"
			+ "              {"
			+ "                \"id\": 500,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 5"
			+ "              }"
			+ "            ]"
			+ "          },"
			+ "          {"
			+ "            \"idTipoContenedor\": 2,"
			+ "            \"denominaciones\": ["
			+ "              {"
			+ "                \"id\": 1000,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 20"
			+ "              },"
			+ "              {"
			+ "                \"id\": 500,"
			+ "                \"idTipoDenominacion\": 2,"
			+ "                \"numeroPiezas\": 5"
			+ "              }"
			+ "            ]"
			+ "          }"
			+ "        ]"
			+ "      }"
			+ "    ]"
			+ "  }"
			+ "}";

	public static final String JSON_REGISTRO = "{"
			+ "  \"mensaje\": \"Operación exitosa\","
			+ "  \"folio\": \"hBEqSEBruJEkjyfiIkEq*03-11-2022 11:36:56\","
			+ "  \"resultado\": {"
			+ "    \"folio\": 1000,"
			+ "    \"mensaje\": \"Registro realizado correctamente\""
			+ "  }"
			+ "}";
	
	public static final String JSON_CONFIRMACION = "{}";
	
	public static final String JSON_CONFIRMACION_INDIVIDUAL = "{"
			+ "  \"mensaje\": \"Operación exitosa\","
			+ "  \"folio\": \"hBEqSEBruJEkjyfiIkEq*03-11-2022 11:36:56\","
			+ "  \"resultado\": {"
			+ "    \"numeroOperacion\": \"2022081955AJTZ0OE\""
			+ "  }"
			+ "}";



}
